language: bash
services: docker

env:
  - VERSION=6.2.0
  
install:
  - git clone https://github.com/manios/docker-varnish.git

before_script:
  - env | sort
  - git checkout v${VERSION} -b v${VERSION}
  - image="varnish:$VERSION"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run -d --name myvarnish -p 6081:6081 manios/varnish:"$VERSION"
  - sleep 5 && nc -zv localhost 6081
  - docker rm -f myvarnish

# vim:set et ts=2 sw=2:
