language: bash
services: docker

env:
  - VERSION=5.2

install:
  - git clone https://github.com/manios/docker-varnish.git

before_script:
  - env | sort
  - cd "$VERSION"
  - image="varnish:$VERSION"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
